### ISSUE TITLE
As a Web Component consumer I want the Realtime Flight Web Component online, to show real time data about the Sky Alps data in my website.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-flightdata-realtime#2]

**Comment by dulvui** [comment]
Webcomponent is now live in testing
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/flightdata-realtime

Everything seems to work fine, also the configurations. Only the Open Data Hub logo on the top is broken.

**Comment by dulvui** [comment]
The webcomponent is now available in production
https://webcomponents.opendatahub.com/webcomponent/flightdata-realtime
